import React from 'react'

const Footer = () => {
  return (
    <footer className="bg-gray-900 text-white mt-12">
      <div className="container mx-auto px-4 py-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div>
            <h3 className="text-xl font-bold mb-4">About Manteiv Daily News</h3>
            <p className="text-gray-400">
              Your premier source for completely fabricated news from the fictional country of Manteiv.
              All stories are AI-generated and 100% fake!
            </p>
          </div>
          
          <div>
            <h3 className="text-xl font-bold mb-4">Disclaimer</h3>
            <p className="text-gray-400">
              This is a satirical website. All articles are fictional and generated by AI.
              Any resemblance to real persons, living or dead, is purely coincidental.
            </p>
          </div>
          
          <div>
            <h3 className="text-xl font-bold mb-4">Tech Stack</h3>
            <p className="text-gray-400">
              Built with FastAPI, React, Tailwind CSS, and powered by AI (Google Gemini/ChatGPT)
            </p>
          </div>
        </div>
        
        <div className="border-t border-gray-800 mt-8 pt-8 text-center text-gray-400">
          <p>&copy; 2026 Manteiv Daily News. All fake rights reserved.</p>
        </div>
      </div>
    </footer>
  )
}

export default Footer
