export const translations = {
  en: {
    // Header
    siteName: "AI Fake Daily News",
    siteSubtitle: "AI-Powered Fake News Network",
    search: "Search",
    home: "Home",
    disclaimer: "DISCLAIMER: All news on this site is 100% FAKE and AI-generated for entertainment!",
    
    // Actions
    generateRandomNews: "Generate Random News",
    generateBillionaireStory: "Generate Billionaire Story",
    generating: "Generating...",
    createNews: "Create AI Fake News",
    createDescription: "Generate randomly or about famous billionaires",
    
    // Stats
    totalArticles: "Total fake articles",
    
    // Sections
    featuredStories: "Featured Stories",
    hotStories: "Hot Stories",
    latestNews: "Latest News",
    
    // Article
    views: "views",
    readMore: "Read more",
    viewMore: "View more",
    backToHome: "Back to home",
    minutesAgo: "minutes ago",
    hoursAgo: "hours ago",
    author: "Author",
    location: "Location",
    publishedDate: "Published",
    tags: "Tags",
    aiGenerated: "AI Generated",
    fakeNews: "Fake News",
    
    // Empty states
    noArticles: "No articles yet!",
    noArticlesDescription: "Click the buttons above to generate AI fake news.",
    noArticlesInCategory: "No articles in",
    noArticlesCategoryDescription: "Return to home page to create new news!",
    
    // Disclaimer
    disclaimerTitle: "Disclaimer",
    disclaimerText: "This article is completely fictional and generated by AI for entertainment purposes only. Any resemblance to real persons, living or dead, or actual events is purely coincidental.",
    infoNote: "Note",
    infoText: "All news on this site is completely fake and created by AI for entertainment purposes. No event is real!",
    
    // Actions
    enjoyedNews: "Enjoyed this fake news? Generate more!",
    generateMore: "Generate More Fake News",
    scrollToTop: "Scroll to top",
    
    // Footer
    aboutTitle: "About AI Fake Daily News",
    aboutDescription: "The premier source for completely fake news generated entirely by artificial intelligence. All stories are fictional and for entertainment only!",
    quickLinks: "Quick Links",
    createNew: "Create New",
    about: "About",
    contact: "Contact",
    technology: "Technology",
    madeWith: "Made with",
    and: "and",
    allRightsReserved: "All fake rights reserved.",
    disclaimerFooter: "This is a satirical website. All articles are fictional and generated by AI. Any resemblance to real persons, living or dead, or actual events is purely coincidental.",
    
    // Category page
    allNews: "All",
    articles: "articles",
    updatedContinuously: "Updated continuously",
    category: "Category",
    
    // Misc
    loading: "Loading",
    articleNotFound: "Article not found",
    loadingArticle: "Loading article..."
  },
  
  vi: {
    // Header
    siteName: "AI Fake Daily News",
    siteSubtitle: "Mạng tin giả do AI tạo ra",
    search: "Tìm kiếm",
    home: "Trang chủ",
    disclaimer: "TUYÊN BỐ: Tất cả tin tức trên trang này là 100% GIẢ MẠO và do AI tạo ra cho mục đích giải trí!",
    
    // Actions
    generateRandomNews: "Tạo tin ngẫu nhiên",
    generateBillionaireStory: "Tạo tin về tỷ phú",
    generating: "Đang tạo...",
    createNews: "Tạo tin tức giả AI",
    createDescription: "Tạo ngẫu nhiên hoặc về tỷ phú nổi tiếng",
    
    // Stats
    totalArticles: "Tổng số bài viết giả",
    
    // Sections
    featuredStories: "Tin nổi bật",
    hotStories: "Tin hot",
    latestNews: "Tin mới nhất",
    
    // Article
    views: "lượt xem",
    readMore: "Đọc thêm",
    viewMore: "Xem thêm",
    backToHome: "Về trang chủ",
    minutesAgo: "phút trước",
    hoursAgo: "giờ trước",
    author: "Tác giả",
    location: "Địa điểm",
    publishedDate: "Xuất bản",
    tags: "Chủ đề",
    aiGenerated: "AI Tạo",
    fakeNews: "Tin Giả",
    
    // Empty states
    noArticles: "Chưa có bài viết nào!",
    noArticlesDescription: "Nhấn nút bên trên để tạo tin tức giả AI.",
    noArticlesInCategory: "Chưa có bài viết nào trong chủ đề",
    noArticlesCategoryDescription: "Hãy quay lại trang chủ để tạo tin tức mới!",
    
    // Disclaimer
    disclaimerTitle: "Tuyên bố từ chối trách nhiệm",
    disclaimerText: "Bài viết này hoàn toàn là hư cấu và được tạo bởi AI chỉ nhằm mục đích giải trí. Bất kỳ sự giống nhau nào với người thật, sống hay đã chết, hoặc các sự kiện thực tế đều là ngẫu nhiên.",
    infoNote: "Lưu ý",
    infoText: "Tất cả tin tức trên trang này đều là hoàn toàn giả mạo và được tạo bởi AI cho mục đích giải trí. Không có sự kiện nào là có thật!",
    
    // Actions
    enjoyedNews: "Thích tin giả này? Tạo thêm nhiều bài nữa!",
    generateMore: "Tạo thêm tin giả",
    scrollToTop: "Lên đầu trang",
    
    // Footer
    aboutTitle: "Về AI Fake Daily News",
    aboutDescription: "Nguồn tin tức giả hàng đầu được tạo hoàn toàn bởi trí tuệ nhân tạo. Tất cả các câu chuyện đều là hư cấu và chỉ nhằm mục đích giải trí!",
    quickLinks: "Liên kết nhanh",
    createNew: "Tạo tin mới",
    about: "Giới thiệu",
    contact: "Liên hệ",
    technology: "Công nghệ",
    madeWith: "Làm với",
    and: "và",
    allRightsReserved: "Tất cả các quyền giả mạo được bảo lưu.",
    disclaimerFooter: "Đây là một trang web mang tính châm biếm. Tất cả các bài viết đều là hư cấu và được tạo bởi AI. Bất kỳ sự giống nhau nào với người thật, sống hay đã chết, hoặc các sự kiện thực tế đều là ngẫu nhiên.",
    
    // Category page
    allNews: "Tất cả tin tức giả mạo về chủ đề",
    articles: "bài viết",
    updatedContinuously: "Cập nhật liên tục",
    category: "Chủ đề",
    
    // Misc
    loading: "Đang tải",
    articleNotFound: "Không tìm thấy bài viết",
    loadingArticle: "Đang tải bài viết..."
  }
}
